<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2_X2wD2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2.x2wD2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2.x2wD2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Sport' => ['privates', '.errored..service_locator.2.x2wD2.App\\Entity\\Sport', NULL, 'Cannot autowire service ".service_locator.2.x2wD2": it references class "App\\Entity\\Sport" but no such service exists.'],
            'SportRepository' => ['privates', 'App\\Repository\\SportRepository', 'getSportRepositoryService', true],
        ], [
            'Sport' => 'App\\Entity\\Sport',
            'SportRepository' => 'App\\Repository\\SportRepository',
        ]);
    }
}
