<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I74Me30Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i74Me30' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i74Me30'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'back' => ['privates', '.errored..service_locator.i74Me30.App\\Entity\\Back', NULL, 'Cannot autowire service ".service_locator.i74Me30": it references class "App\\Entity\\Back" but no such service exists.'],
        ], [
            'back' => 'App\\Entity\\Back',
        ]);
    }
}
