<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ok9Z_NwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ok9Z.nw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ok9Z.nw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'SportRepository' => ['privates', 'App\\Repository\\SportRepository', 'getSportRepositoryService', true],
        ], [
            'SportRepository' => 'App\\Repository\\SportRepository',
        ]);
    }
}
