<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGR57zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P_GR57z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P_GR57z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'backRepository' => ['privates', 'App\\Repository\\BackRepository', 'getBackRepositoryService', true],
        ], [
            'backRepository' => 'App\\Repository\\BackRepository',
        ]);
    }
}
