<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XIIsoltService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xIIsolt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xIIsolt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'back' => ['privates', '.errored..service_locator.xIIsolt.App\\Entity\\Back', NULL, 'Cannot autowire service ".service_locator.xIIsolt": it references class "App\\Entity\\Back" but no such service exists.'],
            'backRepository' => ['privates', 'App\\Repository\\BackRepository', 'getBackRepositoryService', true],
        ], [
            'back' => 'App\\Entity\\Back',
            'backRepository' => 'App\\Repository\\BackRepository',
        ]);
    }
}
