<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5S1j0scService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5S1j0sc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5S1j0sc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Sport' => ['privates', '.errored..service_locator.5S1j0sc.App\\Entity\\Sport', NULL, 'Cannot autowire service ".service_locator.5S1j0sc": it references class "App\\Entity\\Sport" but no such service exists.'],
        ], [
            'Sport' => 'App\\Entity\\Sport',
        ]);
    }
}
