<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GguI4mFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gguI4mF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gguI4mF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rc' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\ActualiteRepository', 'getActualiteRepositoryService', true],
        ], [
            'rc' => 'App\\Repository\\CategorieRepository',
            'repository' => 'App\\Repository\\ActualiteRepository',
        ]);
    }
}
