<?php

namespace ContainerXLtWXhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSport2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5S1j0sc.App\Entity\Sport' shared service.
     *
     * @return \App\Entity\Sport
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5S1j0sc": it references class "App\\Entity\\Sport" but no such service exists.');
    }
}
