<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F9VcekHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f9VcekH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f9VcekH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'EquipeRepository' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
        ], [
            'EquipeRepository' => 'App\\Repository\\EquipeRepository',
        ]);
    }
}
