<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q9gMP9_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q9gMP9.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q9gMP9.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'athlete' => ['privates', '.errored..service_locator.q9gMP9..App\\Entity\\Athlete', NULL, 'Cannot autowire service ".service_locator.q9gMP9.": it references class "App\\Entity\\Athlete" but no such service exists.'],
        ], [
            'athlete' => 'App\\Entity\\Athlete',
        ]);
    }
}
