<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5lo_JgcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5lo.Jgc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5lo.Jgc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['services', 'swiftmailer.mailer.default', 'getSwiftmailer_Mailer_DefaultService', true],
            'tournoiRepository' => ['privates', 'App\\Repository\\TournoiRepository', 'getTournoiRepositoryService', true],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'tournoiRepository' => 'App\\Repository\\TournoiRepository',
        ]);
    }
}
