<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z6oxR2CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z6oxR2C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z6oxR2C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Equipe' => ['privates', '.errored..service_locator.z6oxR2C.App\\Entity\\Equipe', NULL, 'Cannot autowire service ".service_locator.z6oxR2C": it references class "App\\Entity\\Equipe" but no such service exists.'],
        ], [
            'Equipe' => 'App\\Entity\\Equipe',
        ]);
    }
}
