<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SRNl6dNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sRNl6dN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sRNl6dN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tournoi' => ['privates', '.errored..service_locator.sRNl6dN.App\\Entity\\Tournoi', NULL, 'Cannot autowire service ".service_locator.sRNl6dN": it references class "App\\Entity\\Tournoi" but no such service exists.'],
        ], [
            'tournoi' => 'App\\Entity\\Tournoi',
        ]);
    }
}
