<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Eehxy7OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eehxy7O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eehxy7O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Equipe' => ['privates', '.errored..service_locator.eehxy7O.App\\Entity\\Equipe', NULL, 'Cannot autowire service ".service_locator.eehxy7O": it references class "App\\Entity\\Equipe" but no such service exists.'],
            'EquipeRepository' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
        ], [
            'Equipe' => 'App\\Entity\\Equipe',
            'EquipeRepository' => 'App\\Repository\\EquipeRepository',
        ]);
    }
}
