<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sum3bffService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sum3bff' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sum3bff'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'abonnement' => ['privates', '.errored..service_locator.sum3bff.App\\Entity\\Abonnement', NULL, 'Cannot autowire service ".service_locator.sum3bff": it references class "App\\Entity\\Abonnement" but no such service exists.'],
        ], [
            'abonnement' => 'App\\Entity\\Abonnement',
        ]);
    }
}
