<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BIaGlRIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BIaGlRI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BIaGlRI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tournoi' => ['privates', '.errored..service_locator.BIaGlRI.App\\Entity\\Tournoi', NULL, 'Cannot autowire service ".service_locator.BIaGlRI": it references class "App\\Entity\\Tournoi" but no such service exists.'],
            'tournoiRepository' => ['privates', 'App\\Repository\\TournoiRepository', 'getTournoiRepositoryService', true],
        ], [
            'tournoi' => 'App\\Entity\\Tournoi',
            'tournoiRepository' => 'App\\Repository\\TournoiRepository',
        ]);
    }
}
