<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAthlete2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q9gMP9..App\Entity\Athlete' shared service.
     *
     * @return \App\Entity\Athlete
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.q9gMP9.": it references class "App\\Entity\\Athlete" but no such service exists.');
    }
}
