<?php

namespace ContainerEGtu14v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i74Me30.App\Entity\Back' shared service.
     *
     * @return \App\Entity\Back
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.i74Me30": it references class "App\\Entity\\Back" but no such service exists.');
    }
}
