twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
    - bootstrap_5_layout.html.twig

    

when@test:
    twig:
        strict_variables: true
        twig:
    # ...
    filters:
        base64_encode: base64_encode

       