<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGtu14v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGtu14v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGtu14v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGtu14v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEGtu14v\App_KernelDevDebugContainer([
    'container.build_hash' => 'EGtu14v',
    'container.build_id' => '5342ab1e',
    'container.build_time' => 1678436830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGtu14v');
